[tool.poetry]
name = "e-commerce"
version = "0.1.0"
description = ""
authors = ["vovka <@vovka>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pytest = "^8.3.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
